ALTER TABLE agenda_items
ADD COLUMN timer_value INTEGER DEFAULT 0,
ADD COLUMN is_running BOOLEAN DEFAULT FALSE,
ADD COLUMN last_updated TIMESTAMP DEFAULT NOW(),
ADD COLUMN initial_value INTEGER DEFAULT 0; 